apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dalgo.fullname" . }}-celery-worker-default
  labels:
    {{- include "dalgo.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "dalgo.fullname" . }}-celery-worker-default
  template:
    metadata:
      labels:
        app: {{ include "dalgo.fullname" . }}-celery-worker-default
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z {{ include "dalgo.fullname" . }}-postgres {{ .Values.postgres.port }}; do echo waiting for postgres; sleep 2; done']
        - name: wait-for-redis
          image: busybox
          command: ['sh', '-c', 'until nc -z {{ include "dalgo.fullname" . }}-redis {{ .Values.redis.port }}; do echo waiting for redis; sleep 2; done']
      containers:
        - name: celery-worker
          image: "{{ .Values.images.backend.repository }}:{{ .Values.images.backend.tag }}"
          imagePullPolicy: {{ .Values.images.backend.pullPolicy }}
          command: ["celery", "-A", "ddpui", "worker", "-Q", "default", "-n", "ddpui", "-l", "info"]
          envFrom:
            - configMapRef:
                name: {{ include "dalgo.fullname" . }}-config
          env:
            - name: DJANGOSECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "dalgo.fullname" . }}-secrets
                  key: DJANGOSECRET
            - name: DBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dalgo.fullname" . }}-secrets
                  key: DBPASSWORD
            - name: DBADMINUSER
              valueFrom:
                secretKeyRef:
                  name: {{ include "dalgo.fullname" . }}-secrets
                  key: DBADMINUSER
            - name: DBADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dalgo.fullname" . }}-secrets
                  key: DBADMINPASSWORD
            - name: AIRBYTE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "dalgo.fullname" . }}-secrets
                  key: AIRBYTE_API_TOKEN
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dalgo.fullname" . }}-celery-worker-canvas
  labels:
    {{- include "dalgo.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "dalgo.fullname" . }}-celery-worker-canvas
  template:
    metadata:
      labels:
        app: {{ include "dalgo.fullname" . }}-celery-worker-canvas
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z {{ include "dalgo.fullname" . }}-postgres {{ .Values.postgres.port }}; do echo waiting for postgres; sleep 2; done']
        - name: wait-for-redis
          image: busybox
          command: ['sh', '-c', 'until nc -z {{ include "dalgo.fullname" . }}-redis {{ .Values.redis.port }}; do echo waiting for redis; sleep 2; done']
      containers:
        - name: celery-worker-canvas
          image: "{{ .Values.images.backend.repository }}:{{ .Values.images.backend.tag }}"
          imagePullPolicy: {{ .Values.images.backend.pullPolicy }}
          command: ["celery", "-A", "ddpui", "worker", "-Q", "canvas_dbt", "-n", "canvas_dbt", "--concurrency=2", "-l", "info"]
          envFrom:
            - configMapRef:
                name: {{ include "dalgo.fullname" . }}-config
          env:
            - name: DJANGOSECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "dalgo.fullname" . }}-secrets
                  key: DJANGOSECRET
            - name: DBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dalgo.fullname" . }}-secrets
                  key: DBPASSWORD
            - name: DBADMINUSER
              valueFrom:
                secretKeyRef:
                  name: {{ include "dalgo.fullname" . }}-secrets
                  key: DBADMINUSER
            - name: DBADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dalgo.fullname" . }}-secrets
                  key: DBADMINPASSWORD
            - name: AIRBYTE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "dalgo.fullname" . }}-secrets
                  key: AIRBYTE_API_TOKEN
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dalgo.fullname" . }}-celery-beat
  labels:
    {{- include "dalgo.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "dalgo.fullname" . }}-celery-beat
  template:
    metadata:
      labels:
        app: {{ include "dalgo.fullname" . }}-celery-beat
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z {{ include "dalgo.fullname" . }}-postgres {{ .Values.postgres.port }}; do echo waiting for postgres; sleep 2; done']
        - name: wait-for-redis
          image: busybox
          command: ['sh', '-c', 'until nc -z {{ include "dalgo.fullname" . }}-redis {{ .Values.redis.port }}; do echo waiting for redis; sleep 2; done']
      containers:
        - name: celery-beat
          image: "{{ .Values.images.backend.repository }}:{{ .Values.images.backend.tag }}"
          imagePullPolicy: {{ .Values.images.backend.pullPolicy }}
          command: ["celery", "-A", "ddpui", "beat", "-l", "info"]
          envFrom:
            - configMapRef:
                name: {{ include "dalgo.fullname" . }}-config
          env:
            - name: DJANGOSECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "dalgo.fullname" . }}-secrets
                  key: DJANGOSECRET
            - name: DBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dalgo.fullname" . }}-secrets
                  key: DBPASSWORD
            - name: DBADMINUSER
              valueFrom:
                secretKeyRef:
                  name: {{ include "dalgo.fullname" . }}-secrets
                  key: DBADMINUSER
            - name: DBADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dalgo.fullname" . }}-secrets
                  key: DBADMINPASSWORD
            - name: AIRBYTE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "dalgo.fullname" . }}-secrets
                  key: AIRBYTE_API_TOKEN
