{{- if .Values.redis.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dalgo.fullname" . }}-redis
  labels:
    {{- include "dalgo.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "dalgo.fullname" . }}-redis
  template:
    metadata:
      labels:
        app: {{ include "dalgo.fullname" . }}-redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.images.redis.repository }}:{{ .Values.images.redis.tag }}"
          imagePullPolicy: {{ .Values.images.redis.pullPolicy }}
          ports:
            - containerPort: {{ .Values.redis.port }}
              name: redis
{{- if .Values.redis.persistence -}}
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          emptyDir: {}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dalgo.fullname" . }}-redis
  labels:
    {{- include "dalgo.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: redis
      name: redis
  selector:
    app: {{ include "dalgo.fullname" . }}-redis
{{- end }}
