apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dalgo.fullname" . }}-secrets
  labels:
    {{- include "dalgo.labels" . | nindent 4 }}
type: Opaque
data:
  DJANGOSECRET: {{ .Values.djangoSecret | b64enc | quote }}
  DBPASSWORD: {{ .Values.postgres.password | b64enc | quote }}
  DBADMINUSER: {{ .Values.postgres.user | b64enc | quote }}
  DBADMINPASSWORD: {{ .Values.postgres.password | b64enc | quote }}
  AIRBYTE_API_TOKEN: {{ .Values.airbyte.token | b64enc | quote }}
  NEXTAUTH_SECRET: {{ .Values.webapp.nextAuthSecret | b64enc | quote }}
